name: hydra_sweep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.0
  - mlflow=3.0.0
  - hydra-core=1.3.2
  - pip:
    - wandb==0.16.4
    - hydra-joblib-launcher==1.2.0
