name: hydra_sweep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.3.1
  - pytest=8.4.2
  - scipy=1.16.1
  - mlflow=3.2.0
  - hydra-core=1.3.2
  - pip:
      - wandb==0.21.3
      - hydra-joblib-launcher==1.2.0
