name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - requests=2.31.0
  - pip=24.0
  - mlflow=3.0.0
  - hydra-core=1.3.2
  - scikit-learn=1.5.0
  - pandas=3.0.0
  - pyyaml=6.0.1
  - pip:
      - wandb==0.16.4
      - hydra-joblib-launcher==1.2.0
      - omegaconf==2.3.0
