name: process_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - requests=2.32.5
  - pip=24.3.1
  - seaborn=0.13.2
  - pandas=2.3.2
  - scikit-learn=1.7.2
  - matplotlib==3.10.6
  - pillow=11.3.0
  - pip:
      - wandb==0.21.3